# Generated by Django 6.0.6 on 2026-09-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coustomuser',
            managers=[
            ],
        ),
    ]
