# Generated by Django 6.0.6 on 2026-09-22 14:10

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coustomuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coustomuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
