# Generated by Django 6.1 on 2026-08-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coustomuser_address_alter_coustomuser_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField()),
                ('Model', models.CharField()),
                ('year', models.IntegerField()),
                ('Fuel', models.CharField()),
                ('KM_drive', models.IntegerField()),
                ('Title', models.CharField()),
                ('Description', models.CharField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
