# Generated by Django 6.1 on 2026-08-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField()),
                ('Model', models.CharField()),
                ('year', models.IntegerField()),
                ('Title', models.CharField()),
                ('Description', models.CharField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Bikemodel',
            new_name='Bike',
        ),
        migrations.RenameModel(
            old_name='Carmodel',
            new_name='Car',
        ),
    ]
