# Generated by Django 6.1 on 2026-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mobile_rename_bikemodel_bike_rename_carmodel_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField()),
                ('Brand', models.CharField()),
                ('year', models.IntegerField()),
                ('Title', models.CharField()),
                ('Description', models.CharField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
