# Generated by Django 6.1 on 2026-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_electronics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField()),
                ('Author', models.CharField()),
                ('year', models.IntegerField()),
                ('Title', models.CharField()),
                ('Description', models.CharField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
