# Generated by Django 6.1 on 2026-08-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Bikes',
        ),
        migrations.RenameModel(
            old_name='Mobile',
            new_name='Bookss',
        ),
        migrations.RenameModel(
            old_name='Bike',
            new_name='Cars',
        ),
        migrations.RenameModel(
            old_name='Electronics',
            new_name='Electronicss',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Mobiles',
        ),
        migrations.RenameField(
            model_name='bookss',
            old_name='Brand',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='bookss',
            old_name='Model',
            new_name='Book_name',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='Author',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='Book_name',
            new_name='Model',
        ),
    ]
