# Generated by Django 6.1 on 2026-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bookss_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='bookss',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
