# Generated by Django 6.1 on 2026-08-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
