# Generated by Django 6.1 on 2026-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_detail_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
