# Generated by Django 6.1 on 2026-08-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_detail_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Book_Detail',
        ),
    ]
