# Generated by Django 6.1 on 2026-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_detail_book_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookss',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
