# Generated by Django 6.1 on 2026-08-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_bookss_created_at_mobiles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicss',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
