# Generated by Django 6.1 on 2026-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_bikes_created_at_cars_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
