# Generated by Django 6.1 on 2026-08-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_bikes_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicss',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
