# Generated by Django 6.1 on 2026-08-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_electronicss_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronicss',
            old_name='Brand',
            new_name='Brands',
        ),
        migrations.RenameField(
            model_name='electronicss',
            old_name='Item',
            new_name='Items',
        ),
        migrations.RenameField(
            model_name='electronicss',
            old_name='year',
            new_name='years',
        ),
    ]
