# Generated by Django 6.1 on 2026-08-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_brand_electronicss_brands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronicss',
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='electronicss',
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='electronicss',
            old_name='years',
            new_name='year',
        ),
    ]
