# Generated by Django 6.1 on 2026-08-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_brands_electronicss_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicss',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='electronicss',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='electronicss',
            name='Title',
        ),
    ]
