# Generated by Django 6.1 on 2026-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_electronicss_brand_remove_electronicss_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicss',
            name='Brand',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='electronicss',
            name='Items',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='electronicss',
            name='Title',
            field=models.CharField(null=True),
        ),
    ]
