# Generated by Django 6.1 on 2026-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_electronicss_brand_electronicss_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
