# Generated by Django 6.1 on 2026-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_cars_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=100)),
                ('Brand', models.CharField(blank=True, max_length=100, null=True)),
                ('Material', models.CharField(max_length=100)),
                ('Condition', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Images', models.ImageField(blank=True, null=True, upload_to='furniture/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
