# Generated by Django 6.1 on 2026-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_furniture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='Age',
        ),
        migrations.AlterField(
            model_name='furniture',
            name='Description',
            field=models.CharField(),
        ),
    ]
