# Generated by Django 6.1 on 2026-08-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_furniture_age_alter_furniture_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField()),
                ('Model', models.CharField()),
                ('year', models.IntegerField()),
                ('Title', models.CharField()),
                ('Description', models.CharField()),
                ('Price', models.IntegerField()),
                ('Images', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
