# Generated by Django 6.0.6 on 2026-08-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_gadgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Fuel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cars',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
