# Generated by Django 6.0.6 on 2026-08-18 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_cars_brand_alter_cars_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
