# Generated by Django 6.0.6 on 2026-08-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_cars_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='Fuel',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='Images',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='KM_drive',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='Model',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='year',
        ),
    ]
