# Generated by Django 6.0.6 on 2026-08-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_cars_brand_remove_cars_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='seller',
        ),
        migrations.AddField(
            model_name='cars',
            name='Brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='Fuel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='KM_drive',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='Model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='Title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
