# Generated by Django 6.0.6 on 2026-08-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_bikes_seller_book_detail_seller_bookss_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
