# Generated by Django 6.0.6 on 2026-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_coustomuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomuser',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coustomuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
