# Generated by Django 6.1 on 2026-09-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_coustomuser_otp_coustomuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomuser',
            name='Location',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='coustomuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='Title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookss',
            name='Title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicss',
            name='Title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='Title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gadgets',
            name='Title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='Title',
            field=models.CharField(max_length=20),
        ),
    ]
