# Generated by Django 6.1 on 2026-09-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_coustomuser_location_coustomuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='Transmission',
            field=models.CharField(null=True),
        ),
    ]
