# Generated by Django 6.1 on 2026-09-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_cars_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gadgets',
            old_name='Model',
            new_name='Item',
        ),
    ]
