# Generated by Django 6.1 on 2026-09-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_model_gadgets_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='Location',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bikes',
            name='Ownership',
            field=models.IntegerField(null=True),
        ),
    ]
