# Generated by Django 6.1 on 2026-09-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_bikes_location_bikes_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='Title',
        ),
    ]
