# Generated by Django 6.1 on 2026-09-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_bikes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='Price',
            field=models.DecimalField(),
        ),
    ]
