# Generated by Django 6.1 on 2026-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_furniture_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
