# Generated by Django 6.1 on 2026-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_furniture_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='Title',
            field=models.CharField(null=True),
        ),
    ]
