# Generated by Django 6.1 on 2026-09-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_bikes_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='Location',
        ),
    ]
